name: CI Pipeline - Validação de Código

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonando o repositório
      uses: actions/checkout@v4

    - name: ⚙️ Configurando o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📦 Instalando dependências
      run: npm install

    - name: 🔍 Verificando qualidade do código (Lint)
      run: npm run lint

    - name: 🏗️ Testando o Build do projeto
      run: npm run build